### ISSUE TITLE
Comparison with Parquet.jl?

### ISSUE THREAD

**Issue by tlienart** [cjdoris/ARFFFiles.jl#10]
Hello! thanks for this package, I'm not very familiar with ARFF files and was wondering whether it's a similar idea than Parquet files (for which there's a [package](https://github.com/JuliaIO/Parquet.jl)) ? (i.e. columnar stuff with an indication of the eltype of each column)? 

Are the two effectively equivalent in terms of how much information they contain? if so are you aware of advantages for one or the other?

Thanks!

**Comment by cjdoris** [comment]
Use Parquet, it's a much more widespread format, supports more data types and uses a more compact binary representation so is faster to read.

I only wrote this package because some data I needed was only available in ARFF, but I wouldn't recommend writing your data in this format.
