### ISSUE TITLE
Parsing problem when a categorical value contains spaces

### ISSUE THREAD

**Issue by jbrea** [cjdoris/ARFFFiles.jl#19]
see https://github.com/JuliaAI/OpenML.jl/issues/26

**Comment by cjdoris** [comment]
Yeah OK, I see the issue - unquoted strings in ARFFF should have any leading/trailing whitespace ignored, which we are not doing. Should be an easy fix.

**Comment by cjdoris** [comment]
OK fixed, that dataset loads fine now. New version being registered now: https://github.com/JuliaRegistries/General/pull/117679
