### ISSUE TITLE
Allow UTF-8 encoded input

### ISSUE THREAD

**Issue by cjdoris** [cjdoris/ARFFFiles.jl#5]
At openml.org, there are example ARFF files which appear to be UTF-8 encoded, despite the fact that [the ARFF description](https://waikato.github.io/weka-wiki/formats_and_processing/arff_stable/) says that this is an ASCII file format. (See #4)

Rewrite the parser to accept UTF-8 data. That is, consume an `IO` and parse it one `Char` at a time.

**Comment by jbrea** [comment]
I guess it is within string fields that non-ASCII characters are allowed (or just appear). OpenML dataset 379 contains emails in the text field.
